"use client";

import { useEffect } from "react";
import { useSession, signOut } from "next-auth/react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import LoadingScreen from "../components/LoadingScreen";

export default function PricingPage() {
  const { status } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (status === "unauthenticated") router.push("/sign-in");
  }, [status, router]);

  if (status === "loading") return <LoadingScreen />;

  return (
    <main style={S.page}>
      <div style={S.header}>
        <Link href="/procurement" style={S.brand}>BuyRight <span style={{ color: "#0A84FF" }}>AI</span></Link>
        <button onClick={() => signOut({ callbackUrl: "/sign-in" })} style={S.ghostBtn}>Sign out</button>
      </div>

      <div style={S.hero}>
        <div style={S.pill}>Simple pricing</div>
        <h1 style={S.h1}>Free. Forever.</h1>
        <p style={S.sub}>No subscription, no credit card, no catch. Every feature is included at $0.</p>
      </div>

      <div style={S.cardWrap}>
        <div style={S.card}>
          <p style={S.planName}>Everything included</p>
          <p style={S.planPrice}>$0<span style={S.per}>/month</span></p>
          <ul style={S.features}>
            <li style={S.feature}>✓ AI Shopping Advisor</li>
            <li style={S.feature}>✓ Consumer Procurement</li>
            <li style={S.feature}>✓ Fulfillment & Returns</li>
            <li style={S.feature}>✓ Collective Bargaining AI</li>
            <li style={S.feature}>✓ Live price comparison across retailers</li>
            <li style={S.feature}>✓ No credit card required</li>
          </ul>
          <Link href="/procurement" style={S.cta}>Start shopping →</Link>
        </div>
      </div>

      <div style={S.affiliateBox}>
        <p style={S.affiliateHeading}>How we keep the lights on</p>
        <p style={S.affiliateText}>
          When you click a buy link and make a purchase, we may earn a small affiliate commission
          from the retailer — at no extra cost to you. We never recommend a product because of
          affiliate fees; our recommendations are generated by AI and ranked on price and fit, not margins.
        </p>
        <p style={S.affiliateDisclosure}>
          Affiliate disclosure: BuyRight AI participates in affiliate programs with Amazon, Best Buy,
          Walmart, Target, and others. This is how we stay free.
        </p>
      </div>

      <p style={S.footer}>BuyRight AI · Free forever · No credit card · No hidden fees</p>
    </main>
  );
}

const S: Record<string, React.CSSProperties> = {
  page:              { minHeight: "100vh", background: "#0C1525", fontFamily: "system-ui", display: "flex", flexDirection: "column", alignItems: "center" },
  header:            { width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", padding: "20px 40px", borderBottom: "1px solid rgba(255,255,255,0.05)" },
  brand:             { color: "#F1F5F9", fontSize: 18, fontWeight: 700, textDecoration: "none" },
  ghostBtn:          { background: "transparent", border: "1px solid rgba(255,255,255,0.1)", color: "#94A3B8", borderRadius: 8, padding: "6px 14px", cursor: "pointer", fontSize: 13 },
  hero:              { textAlign: "center", padding: "60px 24px 40px", maxWidth: 560 },
  pill:              { display: "inline-block", background: "rgba(10,132,255,0.08)", color: "#0A84FF", border: "1px solid rgba(10,132,255,0.2)", borderRadius: 99, padding: "4px 14px", fontSize: 12, fontWeight: 600, marginBottom: 16, textTransform: "uppercase", letterSpacing: "0.5px" },
  h1:                { color: "#F1F5F9", fontSize: 42, fontWeight: 800, margin: "0 0 12px", letterSpacing: "-0.5px" },
  sub:               { color: "#94A3B8", fontSize: 16, lineHeight: 1.6, margin: 0 },
  cardWrap:          { display: "flex", justifyContent: "center", padding: "0 24px 40px" },
  card:              { background: "rgba(255,255,255,0.03)", border: "1px solid rgba(10,132,255,0.3)", borderRadius: 20, padding: "36px 32px", width: 320, display: "flex", flexDirection: "column", gap: 20 },
  planName:          { color: "#94A3B8", fontSize: 13, fontWeight: 600, margin: 0, textTransform: "uppercase", letterSpacing: "0.8px" },
  planPrice:         { color: "#F1F5F9", fontSize: 52, fontWeight: 800, margin: 0 },
  per:               { fontSize: 16, fontWeight: 400, color: "#94A3B8" },
  features:          { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 10, flex: 1 },
  feature:           { color: "#E2E8F0", fontSize: 14 },
  cta:               { background: "#0A84FF", color: "#fff", border: "none", borderRadius: 10, padding: "13px 20px", fontWeight: 700, fontSize: 14, cursor: "pointer", textAlign: "center", textDecoration: "none", display: "block" },
  affiliateBox:      { maxWidth: 560, margin: "0 24px 48px", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: 16, padding: "28px 32px", display: "flex", flexDirection: "column", gap: 12 },
  affiliateHeading:  { color: "#F1F5F9", fontSize: 15, fontWeight: 700, margin: 0 },
  affiliateText:     { color: "#94A3B8", fontSize: 14, lineHeight: 1.7, margin: 0 },
  affiliateDisclosure: { color: "#475569", fontSize: 12, lineHeight: 1.6, margin: 0, borderTop: "1px solid rgba(255,255,255,0.05)", paddingTop: 12 },
  footer:            { color: "#475569", fontSize: 12, paddingBottom: 40 },
};
